language: node_js
sudo: true

node_js:
  - 13

addons:
  apt:
    packages:
      - xvfb
      - rpm

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  
notifications:
  email: false
