[package]
name = "panda-installer"
version = "0.1.0"
authors = ["dzikoysk <dzikoysk@dzikoysk.net>"]
edition = "2018"

[dependencies]
log = "0.4"
pretty_env_logger = "0.4"
iced = { version = "0.1", features = ["canvas"] }